trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- script: git submodule update --init --recursive
  displayName: 'Checkout all submodules'

- script: brew install automake autoconf libtool gettext
  displayName: 'Install build tools'

- script: make
  displayName: 'Build all'

- script: tar -cvJf '$(Build.ArtifactStagingDirectory)/Python.framework-full-$(Build.BuildId).txz' '$(Build.SourcesDirectory)/Python.framework'
  displayName: Make tarball for full Python.framework

- script: |
    make slim
    tar -cvJf '$(Build.ArtifactStagingDirectory)/Python.framework-slim-$(Build.BuildId).txz' '$(Build.SourcesDirectory)/Python.framework'
  displayName: Make tarball for slim Python.framework

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

